version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: delivery_agency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
