import React, { useEffect, useState } from 'react';
import { texts } from './texts';
import {
  login, getMyProductOrders, createProductOrder, getMyShipments, getMyDeliveryTasks, updateDeliveryTaskStatus,
  getProductOrders, getShipments, createDeliveryTask, createShipment, updateShipmentStatus, deleteShipment, deleteProductOrder,
  getUsers, createUser, updateUser, deleteUser
} from './api';

const badge = (s) => ({ WaitingPickup:'warning', PickupAssigned:'info', PickedUp:'primary', ReadyForShipment:'success', ShipmentCreated:'secondary', Cancelled:'danger', Created:'secondary', Processing:'primary', Sent:'info', Delivered:'success', Completed:'success', DeliveredToStorage:'success', InProgress:'primary', Assigned:'info' }[s] || 'dark');

export default function App() {
  const [lang, setLang] = useState('en'); const t = texts[lang];
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user') || 'null'));
  const [message, setMessage] = useState('');
  const [orders, setOrders] = useState([]); const [shipments, setShipments] = useState([]); const [tasks, setTasks] = useState([]); const [users, setUsers] = useState([]);
  const [filters, setFilters] = useState({ search: '', shipmentType: '', currency: '', status: '' });
  const [productForm, setProductForm] = useState({ productName:'', productPrice:'', currency:'USD', preferredShipmentType:'Air', customerName:'', customerPhone:'', pickupAddress:'' });
  const [taskForm, setTaskForm] = useState({ productOrderId:'', deliveryUserId:'4', pickupAddress:'', destinationPoint:'A8', notes:'' });
  const [shipmentForm, setShipmentForm] = useState({ productOrderId:'', shipmentType:'Air', currency:'USD', basePrice:'' });
  const [userForm, setUserForm] = useState({ fullName:'', email:'', phone:'', passwordHash:'', role:'Customer' });

  const saveUser = (u, token) => { localStorage.setItem('token', token); localStorage.setItem('user', JSON.stringify(u)); setUser(u); };
  const logout = () => { localStorage.clear(); setUser(null); setMessage(''); };

  const load = async () => {
    if (!user) return;
    if (user.role === 'Customer') { setOrders(await getMyProductOrders(user.userId)); setShipments(await getMyShipments(user.userId)); }
    if (user.role === 'Delivery') setTasks(await getMyDeliveryTasks(user.userId));
    if (user.role === 'Employee' || user.role === 'Admin') {
      const f = Object.fromEntries(Object.entries(filters).filter(([,v]) => v));
      setOrders(await getProductOrders(f)); setShipments(await getShipments(f));
      if (user.role === 'Admin') setUsers(await getUsers());
    }
  };

  useEffect(() => { load(); }, [user]);

  const doLogin = async (e) => { e.preventDefault(); try { const r = await login(email, password); saveUser({ userId:r.userId, fullName:r.fullName, role:r.role }, r.token); setMessage('Login success'); } catch { setMessage('Login failed'); } };

  const createProduct = async (e) => { e.preventDefault(); await createProductOrder({ ...productForm, productPrice:Number(productForm.productPrice), customerId:user.userId }); setProductForm({ productName:'', productPrice:'', currency:'USD', preferredShipmentType:'Air', customerName:'', customerPhone:'', pickupAddress:'' }); await load(); };
  const createTask = async (e) => { e.preventDefault(); await createDeliveryTask({ ...taskForm, productOrderId:Number(taskForm.productOrderId), deliveryUserId:Number(taskForm.deliveryUserId) }); setTaskForm({ productOrderId:'', deliveryUserId:'4', pickupAddress:'', destinationPoint:'A8', notes:'' }); await load(); };
  const createNewShipment = async (e) => { e.preventDefault(); await createShipment({ ...shipmentForm, productOrderId:Number(shipmentForm.productOrderId), basePrice:Number(shipmentForm.basePrice), createdByUserId:user.userId }); setShipmentForm({ productOrderId:'', shipmentType:'Air', currency:'USD', basePrice:'' }); await load(); };

  if (!user) return <div className="container py-5"><div className="row justify-content-center"><div className="col-md-5 card p-4"><h3>{t.title}</h3><div className="d-flex justify-content-end"><button className="btn btn-sm btn-outline-secondary me-2" onClick={()=>setLang('en')}>EN</button><button className="btn btn-sm btn-outline-secondary" onClick={()=>setLang('ru')}>RU</button></div><form onSubmit={doLogin}><input className="form-control mt-3" placeholder={t.email} value={email} onChange={e=>setEmail(e.target.value)} /><input className="form-control mt-2" type="password" placeholder={t.password} value={password} onChange={e=>setPassword(e.target.value)} /><button className="btn btn-primary mt-3 w-100">{t.login}</button></form>{message && <div className="alert alert-info mt-3">{message}</div>}</div></div></div>;

  const isOps = user.role === 'Employee' || user.role === 'Admin';
  return <div className="container py-3"><div className="d-flex justify-content-between align-items-center"><h4>{t.title} - {user.fullName} ({user.role})</h4><div><button className="btn btn-sm btn-outline-secondary me-2" onClick={()=>setLang('en')}>EN</button><button className="btn btn-sm btn-outline-secondary me-2" onClick={()=>setLang('ru')}>RU</button><button className="btn btn-sm btn-danger" onClick={logout}>{t.logout}</button></div></div>
    {message && <div className="alert alert-info mt-2">{message}</div>}

    {user.role === 'Customer' && <>
      <div className="card mt-3 p-3"><h5>{t.newProduct}</h5><form onSubmit={createProduct} className="row g-2"><div className="col"><input className="form-control" placeholder={t.productName} value={productForm.productName} onChange={e=>setProductForm({...productForm, productName:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.productPrice} value={productForm.productPrice} onChange={e=>setProductForm({...productForm, productPrice:e.target.value})}/></div><div className="col"><select className="form-select" value={productForm.currency} onChange={e=>setProductForm({...productForm, currency:e.target.value})}>{['USD','EUR','RUB','CNY'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col"><select className="form-select" value={productForm.preferredShipmentType} onChange={e=>setProductForm({...productForm, preferredShipmentType:e.target.value})}>{['Air','Sea'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col-12"><input className="form-control" placeholder={t.customerName} value={productForm.customerName} onChange={e=>setProductForm({...productForm, customerName:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.customerPhone} value={productForm.customerPhone} onChange={e=>setProductForm({...productForm, customerPhone:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.pickupAddress} value={productForm.pickupAddress} onChange={e=>setProductForm({...productForm, pickupAddress:e.target.value})}/></div><div className="col"><button className="btn btn-primary w-100">{t.create}</button></div></form></div>
      <div className="card mt-3 p-3"><h5>{t.myOrders}</h5><table className="table table-sm"><thead><tr><th>ID</th><th>{t.productName}</th><th>{t.status}</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.productName}</td><td><span className={`badge text-bg-${badge(o.productStatus)}`}>{o.productStatus}</span></td></tr>)}</tbody></table></div>
      <div className="card mt-3 p-3"><h5>{t.myShipments}</h5><table className="table table-sm"><thead><tr><th>ID</th><th>No</th><th>{t.status}</th></tr></thead><tbody>{shipments.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.shipmentNumber}</td><td><span className={`badge text-bg-${badge(s.shipmentStatus)}`}>{s.shipmentStatus}</span></td></tr>)}</tbody></table></div>
    </>}

    {user.role === 'Delivery' && <div className="card mt-3 p-3"><h5>{t.myTasks}</h5><table className="table table-sm"><thead><tr><th>ID</th><th>{t.productOrderId}</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{tasks.map(d=><tr key={d.id}><td>{d.id}</td><td>{d.productOrderId}</td><td><span className={`badge text-bg-${badge(d.taskStatus)}`}>{d.taskStatus}</span></td><td>{['InProgress','PickedUp','DeliveredToStorage','Completed'].map(s=><button key={s} className="btn btn-sm btn-outline-primary me-1" onClick={async()=>{await updateDeliveryTaskStatus(d.id,s,''); await load();}}>{s}</button>)}</td></tr>)}</tbody></table></div>}

    {isOps && <>
      <div className="row mt-3 g-2"><div className="col"><div className="card p-2">Orders: {orders.length}</div></div><div className="col"><div className="card p-2">WaitingPickup: {orders.filter(o=>o.productStatus==='WaitingPickup').length}</div></div><div className="col"><div className="card p-2">ReadyForShipment: {orders.filter(o=>o.productStatus==='ReadyForShipment').length}</div></div><div className="col"><div className="card p-2">Active shipments: {shipments.filter(s=>s.shipmentStatus!=='Delivered' && s.shipmentStatus!=='Cancelled').length}</div></div></div>
      <div className="card mt-3 p-3"><div className="row g-2"><div className="col"><input className="form-control" placeholder={t.search} value={filters.search} onChange={e=>setFilters({...filters, search:e.target.value})} /></div><div className="col"><select className="form-select" value={filters.shipmentType} onChange={e=>setFilters({...filters, shipmentType:e.target.value})}><option value="">All shipment types</option><option>Air</option><option>Sea</option></select></div><div className="col"><select className="form-select" value={filters.currency} onChange={e=>setFilters({...filters, currency:e.target.value})}><option value="">All currencies</option>{['USD','EUR','RUB','CNY'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col"><select className="form-select" value={filters.status} onChange={e=>setFilters({...filters, status:e.target.value})}><option value="">All statuses</option><option>WaitingPickup</option><option>PickupAssigned</option><option>PickedUp</option><option>ReadyForShipment</option><option>ShipmentCreated</option></select></div><div className="col"><button className="btn btn-secondary w-100" onClick={load}>{t.applyFilters}</button></div></div></div>
      <div className="card mt-3 p-3"><h5>{t.orders}</h5><table className="table table-sm"><thead><tr><th>ID</th><th>{t.productName}</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.productName}</td><td><span className={`badge text-bg-${badge(o.productStatus)}`}>{o.productStatus}</span></td><td><button className="btn btn-sm btn-outline-danger" onClick={async()=>{await deleteProductOrder(o.id); await load();}}>Delete</button></td></tr>)}</tbody></table></div>
      <div className="card mt-3 p-3"><h5>{t.assignTask}</h5><form onSubmit={createTask} className="row g-2"><div className="col"><input className="form-control" placeholder={t.productOrderId} value={taskForm.productOrderId} onChange={e=>setTaskForm({...taskForm, productOrderId:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.deliveryUserId} value={taskForm.deliveryUserId} onChange={e=>setTaskForm({...taskForm, deliveryUserId:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.pickupAddress} value={taskForm.pickupAddress} onChange={e=>setTaskForm({...taskForm, pickupAddress:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.destinationPoint} value={taskForm.destinationPoint} onChange={e=>setTaskForm({...taskForm, destinationPoint:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.notes} value={taskForm.notes} onChange={e=>setTaskForm({...taskForm, notes:e.target.value})}/></div><div className="col"><button className="btn btn-primary w-100">{t.create}</button></div></form></div>
      <div className="card mt-3 p-3"><h5>{t.createShipment}</h5><form onSubmit={createNewShipment} className="row g-2"><div className="col"><input className="form-control" placeholder={t.productOrderId} value={shipmentForm.productOrderId} onChange={e=>setShipmentForm({...shipmentForm, productOrderId:e.target.value})}/></div><div className="col"><select className="form-select" value={shipmentForm.shipmentType} onChange={e=>setShipmentForm({...shipmentForm, shipmentType:e.target.value})}><option>Air</option><option>Sea</option></select></div><div className="col"><select className="form-select" value={shipmentForm.currency} onChange={e=>setShipmentForm({...shipmentForm, currency:e.target.value})}>{['USD','EUR','RUB','CNY'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col"><input className="form-control" placeholder={t.basePrice} value={shipmentForm.basePrice} onChange={e=>setShipmentForm({...shipmentForm, basePrice:e.target.value})}/></div><div className="col"><button className="btn btn-success w-100">{t.create}</button></div></form></div>
      <div className="card mt-3 p-3"><h5>{t.shipments}</h5><table className="table table-sm"><thead><tr><th>ID</th><th>No</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{shipments.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.shipmentNumber}</td><td><span className={`badge text-bg-${badge(s.shipmentStatus)}`}>{s.shipmentStatus}</span></td><td>{['Processing','Sent','Delivered','Cancelled'].map(st=><button key={st} className="btn btn-sm btn-outline-primary me-1" onClick={async()=>{await updateShipmentStatus(s.id, st); await load();}}>{st}</button>)}<button className="btn btn-sm btn-outline-danger" onClick={async()=>{await deleteShipment(s.id); await load();}}>Delete</button></td></tr>)}</tbody></table></div>
    </>}

    {user.role === 'Admin' && <div className="card mt-3 p-3"><h5>{t.users}</h5><form className="row g-2" onSubmit={async(e)=>{e.preventDefault(); await createUser(userForm); setUserForm({ fullName:'', email:'', phone:'', passwordHash:'', role:'Customer' }); await load();}}><div className="col"><input className="form-control" placeholder={t.fullName} value={userForm.fullName} onChange={e=>setUserForm({...userForm, fullName:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.email} value={userForm.email} onChange={e=>setUserForm({...userForm, email:e.target.value})}/></div><div className="col"><input className="form-control" placeholder="Phone" value={userForm.phone} onChange={e=>setUserForm({...userForm, phone:e.target.value})}/></div><div className="col"><input className="form-control" placeholder={t.password} value={userForm.passwordHash} onChange={e=>setUserForm({...userForm, passwordHash:e.target.value})}/></div><div className="col"><select className="form-select" value={userForm.role} onChange={e=>setUserForm({...userForm, role:e.target.value})}>{['Admin','Customer','Employee','Delivery'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col"><button className="btn btn-primary w-100">{t.create}</button></div></form>
      <table className="table table-sm mt-3"><thead><tr><th>ID</th><th>{t.fullName}</th><th>{t.email}</th><th>{t.role}</th><th>{t.actions}</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.id}</td><td>{u.fullName}</td><td>{u.email}</td><td>{u.role}</td><td><button className="btn btn-sm btn-outline-secondary me-1" onClick={async()=>{await updateUser(u.id,{...u, passwordHash:''}); await load();}}>Quick Save</button><button className="btn btn-sm btn-outline-danger" onClick={async()=>{await deleteUser(u.id); await load();}}>Delete</button></td></tr>)}</tbody></table></div>}
  </div>;
}
